# Plagiarism Detection Model

Now that you've created training and test data, you are ready to define and train a model. Your goal in this notebook, will be to train a binary classification model that learns to label an answer file as either plagiarized or not, based on the features you provide the model.

This task will be broken down into a few discrete steps:

* Upload your data to S3.
* Define a binary classification model and a training script.
* Train your model and deploy it.
* Evaluate your deployed classifier and answer some questions about your approach.

To complete this notebook, you'll have to complete all given exercises and answer all the questions in this notebook.
> All your tasks will be clearly labeled **EXERCISE** and questions as **QUESTION**.

It will be up to you to explore different classification models and decide on a model that gives you the best performance for this dataset.

---

## Load Data to S3

In the last notebook, you should have created two files: a `training.csv` and `test.csv` file with the features and class labels for the given corpus of plagiarized/non-plagiarized text data. 

>The below cells load in some AWS SageMaker libraries and creates a default bucket. After creating this bucket, you can upload your locally stored data to S3.

Save your train and test `.csv` feature files, locally. To do this you can run the second notebook "2_Plagiarism_Feature_Engineering" in SageMaker or you can manually upload your files to this notebook using the upload icon in Jupyter Lab. Then you can upload local files to S3 by using `sagemaker_session.upload_data` and pointing directly to where the training data is saved.

In [1]:
import pandas as pd
import boto3
import sagemaker

In [2]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# session and role
sagemaker_session = sagemaker.Session()
role = sagemaker.get_execution_role()

# create an S3 bucket
bucket = sagemaker_session.default_bucket()

## EXERCISE: Upload your training data to S3

Specify the `data_dir` where you've saved your `train.csv` file. Decide on a descriptive `prefix` that defines where your data will be uploaded in the default S3 bucket. Finally, create a pointer to your training data by calling `sagemaker_session.upload_data` and passing in the required parameters. It may help to look at the [Session documentation](https://sagemaker.readthedocs.io/en/stable/session.html#sagemaker.session.Session.upload_data) or previous SageMaker code examples.

You are expected to upload your entire directory. Later, the training script will only access the `train.csv` file.

In [3]:
# should be the name of directory you created to save your features data
data_dir = 'plagiarism_data'

# set prefix, a descriptive name for a directory  
prefix = 'plagiarism'

# upload all data to S3
input_data = sagemaker_session.upload_data(data_dir, bucket, prefix)

### Test cell

Test that your data has been successfully uploaded. The below cell prints out the items in your S3 bucket and will throw an error if it is empty. You should see the contents of your `data_dir` and perhaps some checkpoints. If you see any other files listed, then you may have some old model files that you can delete via the S3 console (though, additional files shouldn't affect the performance of model developed in this notebook).

In [4]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# confirm that data is in S3 bucket
empty_check = []
for obj in boto3.resource('s3').Bucket(bucket).objects.all():
    empty_check.append(obj.key)
    print(obj.key)

assert len(empty_check) !=0, 'S3 bucket is empty.'
print('Test passed!')

plagiarism/sagemaker-pytorch-2020-03-28-10-56-48-204/output/model.tar.gz
plagiarism/sagemaker-pytorch-2020-03-28-13-38-12-230/debug-output/training_job_end.ts
plagiarism/sagemaker-pytorch-2020-03-28-13-38-12-230/output/model.tar.gz
plagiarism/sagemaker-pytorch-2020-03-28-16-27-35-152/debug-output/training_job_end.ts
plagiarism/sagemaker-pytorch-2020-03-28-16-27-35-152/output/model.tar.gz
plagiarism/sagemaker-pytorch-2020-03-29-10-35-14-765/debug-output/training_job_end.ts
plagiarism/sagemaker-pytorch-2020-03-29-10-35-14-765/output/model.tar.gz
plagiarism/sagemaker-pytorch-2020-03-29-15-48-08-076/debug-output/training_job_end.ts
plagiarism/sagemaker-pytorch-2020-03-29-15-48-08-076/output/model.tar.gz
plagiarism/sagemaker-pytorch-2020-04-01-18-40-21-089/debug-output/training_job_end.ts
plagiarism/sagemaker-pytorch-2020-04-01-18-40-21-089/output/model.tar.gz
plagiarism/sagemaker-pytorch-2020-04-01-18-52-23-726/debug-output/training_job_end.ts
plagiarism/sagemaker-pytorch-2020-04-01-18-52-

---

# Modeling

Now that you've uploaded your training data, it's time to define and train a model!

The type of model you create is up to you. For a binary classification task, you can choose to go one of three routes:
* Use a built-in classification algorithm, like LinearLearner.
* Define a custom Scikit-learn classifier, a comparison of models can be found [here](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html).
* Define a custom PyTorch neural network classifier. 

It will be up to you to test out a variety of models and choose the best one. Your project will be graded on the accuracy of your final model. 
 
---

## EXERCISE: Complete a training script 

To implement a custom classifier, you'll need to complete a `train.py` script. You've been given the folders `source_sklearn` and `source_pytorch` which hold starting code for a custom Scikit-learn model and a PyTorch model, respectively. Each directory has a `train.py` training script. To complete this project **you only need to complete one of these scripts**; the script that is responsible for training your final model.

A typical training script:
* Loads training data from a specified directory
* Parses any training & model hyperparameters (ex. nodes in a neural network, training epochs, etc.)
* Instantiates a model of your design, with any specified hyperparams
* Trains that model 
* Finally, saves the model so that it can be hosted/deployed, later

### Defining and training a model
Much of the training script code is provided for you. Almost all of your work will be done in the `if __name__ == '__main__':` section. To complete a `train.py` file, you will:
1. Import any extra libraries you need
2. Define any additional model training hyperparameters using `parser.add_argument`
2. Define a model in the `if __name__ == '__main__':` section
3. Train the model in that same section

Below, you can use `!pygmentize` to display an existing `train.py` file. Read through the code; all of your tasks are marked with `TODO` comments. 

**Note: If you choose to create a custom PyTorch model, you will be responsible for defining the model in the `model.py` file,** and a `predict.py` file is provided. If you choose to use Scikit-learn, you only need a `train.py` file; you may import a classifier from the `sklearn` library.

In [ ]:
# directory can be changed to: source_sklearn or source_pytorch
!pygmentize source_pytorch/train.py

### Provided code

If you read the code above, you can see that the starter code includes a few things:
* Model loading (`model_fn`) and saving code
* Getting SageMaker's default hyperparameters
* Loading the training data by name, `train.csv` and extracting the features and labels, `train_x`, and `train_y`

If you'd like to read more about model saving with [joblib for sklearn](https://scikit-learn.org/stable/modules/model_persistence.html) or with [torch.save](https://pytorch.org/tutorials/beginner/saving_loading_models.html), click on the provided links.

---
# Create an Estimator

When a custom model is constructed in SageMaker, an entry point must be specified. This is the Python file which will be executed when the model is trained; the `train.py` function you specified above. To run a custom training script in SageMaker, construct an estimator, and fill in the appropriate constructor arguments:

* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `source_sklearn` OR `source_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training and prediction.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **entry_point**: The path to the Python script SageMaker runs for training.
* **source_dir**: The path to the training script directory `train_sklearn` OR `train_pytorch`.
* **role**: Role ARN, which was specified, above.
* **train_instance_count**: The number of training instances (should be left at 1).
* **train_instance_type**: The type of SageMaker instance for training. Note: Because Scikit-learn does not natively support GPU training, Sagemaker Scikit-learn does not currently support training on GPU instance types.
* **sagemaker_session**: The session used to train on Sagemaker.
* **hyperparameters** (optional): A dictionary `{'name':value, ..}` passed to the train function as hyperparameters.

Note: For a PyTorch model, there is another optional argument **framework_version**, which you can set to the latest version of PyTorch, `1.0`.

## EXERCISE: Define a Scikit-learn or PyTorch estimator

To import your desired estimator, use one of the following lines:
```
from sagemaker.sklearn.estimator import SKLearn
```
```
from sagemaker.pytorch import PyTorch
```

In [ ]:
# If you are going to use a SKLearn estimator run this code

# your import and estimator code, here
from sagemaker.sklearn.estimator import SKLearn

estimator = SKLearn(entry_point='train.py',
                    source_dir='source_sklearn',
                    role=role,
                    train_instance_count=1,
                    train_instance_type='ml.c4.xlarge',
                    sagemaker_session=sagemaker_session)
#                    hyperparameters={
#                        'C': 10})

In [27]:
del estimator

In [28]:
# If you are going to use a Pytorch estimator run this code

# your import and estimator code, here
from sagemaker.pytorch import PyTorch

try: 
    print('Created SKLearn estimator: ',estimator)
except:
    # Set an output path:
    output_path = 's3://{}/{}'.format(bucket, prefix)

    # instantiate a pytorch estimator
    estimator = PyTorch(entry_point='train.py',
                    source_dir='source_pytorch',
                    role=role,
                    framework_version='1.0',
                    train_instance_count=1,
                    train_instance_type='ml.c4.xlarge',
                    output_path=input_data,
                    sagemaker_session=sagemaker_session,
                    hyperparameters={
                        'input_features': 5,
                        'hidden_dim': 200,
                        'output_dim': 4,
                        'epochs': 500
                    })

## EXERCISE: Train the estimator

Train your estimator on the training data stored in S3. This should create a training job that you can monitor in your SageMaker console.

In [29]:
%%time

# Train your estimator on S3 training data
estimator.fit({'train': input_data})


2020-04-02 20:42:18 Starting - Starting the training job...
2020-04-02 20:42:46 Starting - Launching requested ML instances.........
2020-04-02 20:43:53 Starting - Preparing the instances for training......
2020-04-02 20:45:07 Downloading - Downloading input data
2020-04-02 20:45:07 Training - Downloading the training image..bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2020-04-02 20:45:27,470 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2020-04-02 20:45:27,473 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-02 20:45:27,485 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2020-04-02 20:45:27,486 sagemaker_pytorch_container.training INFO     Invoking user training script.
2020-04-02 20:45:27,848 sagemaker-containers INFO     Module train does not provide a setup.py. 
Generating setup.py
2020-04-02 20:45:27,


2020-04-02 20:45:45 Uploading - Uploading generated training model
2020-04-02 20:45:45 Completed - Training job completed
Training seconds: 54
Billable seconds: 54
CPU times: user 563 ms, sys: 44.9 ms, total: 608 ms
Wall time: 3min 42s


## EXERCISE: Deploy the trained model

After training, deploy your model to create a `predictor`. If you're using a PyTorch model, you'll need to create a trained `PyTorchModel` that accepts the trained `<model>.model_data` as an input parameter and points to the provided `source_pytorch/predict.py` file as an entry point. 

To deploy a trained model, you'll use `<model>.deploy`, which takes in two arguments:
* **initial_instance_count**: The number of deployed instances (1).
* **instance_type**: The type of SageMaker instance for deployment.

Note: If you run into an instance error, it may be because you chose the wrong training or deployment instance_type. It may help to refer to your previous exercise code to see which types of instances we used.

In [30]:
%%time

if estimator.train_image().find('pytorch')>0:
    print('Deploying Pytorch Model')
# uncomment, if needed
    from sagemaker.pytorch import PyTorchModel
    
    model = PyTorchModel(model_data=estimator.model_data,
                         entry_point='predict.py',
                         source_dir='source_pytorch',
                         framework_version='1.3.1',
                         role=role)
    
    predictor = model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')
else:
    print('Deploying SKLearn Model')
# deploy your model to create a predictor
    predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

Deploying Pytorch Model
---------------!CPU times: user 464 ms, sys: 23.2 ms, total: 488 ms
Wall time: 7min 32s


---
# Evaluating Your Model

Once your model is deployed, you can see how it performs when applied to our test data.

The provided cell below, reads in the test data, assuming it is stored locally in `data_dir` and named `test.csv`. The labels and features are extracted from the `.csv` file.

In [31]:
"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
import os

# read in test data, assuming it is stored locally
test_data = pd.read_csv(os.path.join(data_dir, "test.csv"), header=None, names=None)

# labels are in the first column
test_y = test_data.iloc[:,0]
test_x = test_data.iloc[:,1:]

## EXERCISE: Determine the accuracy of your model

Use your deployed `predictor` to generate predicted, class labels for the test data. Compare those to the *true* labels, `test_y`, and calculate the accuracy as a value between 0 and 1.0 that indicates the fraction of test data that your model classified correctly. You may use [sklearn.metrics](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.metrics) for this calculation.

**To pass this project, your model should get at least 90% test accuracy.**

In [32]:
# First: generate predicted, class labels
test_y_preds = predictor.predict(test_x)


"""
DON'T MODIFY ANYTHING IN THIS CELL THAT IS BELOW THIS LINE
"""
# test that your model generates the correct number of labels
assert len(test_y_preds)==len(test_y), 'Unexpected number of predictions.'
print('Test passed!')

Test passed!


In [33]:
test_y_preds

array([[1.1058668e-14, 2.8571721e-02, 7.0119597e-02, 9.0130872e-01],
       [1.1855091e-11, 8.1981689e-02, 1.3988987e-01, 7.7812850e-01],
       [1.7010909e-05, 3.0146870e-01, 6.9589990e-01, 2.6144048e-03],
       [9.7391598e-02, 6.6695797e-01, 2.0513216e-01, 3.0518167e-02],
       [3.7490577e-06, 2.3147473e-01, 5.7518405e-01, 1.9333746e-01],
       [4.5580034e-18, 9.3014389e-03, 4.3561287e-02, 9.4713724e-01],
       [8.5274249e-01, 1.8950609e-02, 7.2567415e-04, 1.2758118e-01],
       [9.0443981e-01, 4.8784681e-02, 2.3989403e-03, 4.4376548e-02],
       [7.7170509e-01, 1.7103335e-01, 1.8019862e-02, 3.9241727e-02],
       [9.2612576e-01, 5.0436627e-02, 2.6291425e-03, 2.0808488e-02],
       [8.7674135e-01, 9.1088697e-02, 5.9951316e-03, 2.6174759e-02],
       [9.2803496e-01, 2.3954671e-02, 1.1505404e-03, 4.6859857e-02],
       [7.7423230e-03, 6.6947603e-01, 3.1620738e-01, 6.5742750e-03],
       [2.5708656e-12, 6.9214791e-02, 2.0388588e-01, 7.2689933e-01],
       [2.5664131e-15, 2.4108907e-

In [11]:
import numpy as np
np.argmax(test_y_preds, axis=1)

array([3, 3, 2, 1, 2, 3, 0, 0, 0, 0, 0, 0, 1, 3, 3, 2, 2, 3, 0, 3, 0, 3,
       3, 0, 0])

In [37]:
# Second: calculate the test accuracy
#from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix, accuracy_score
import numpy as np

#accuracy = accuracy_score(test_y, test_y_preds)
#print(accuracy)

### UPDATED ###
# Calculate the predicted clas
test_y_classes = np.argmax(test_y_preds, axis=1)
cm = confusion_matrix(test_y, test_y_classes)
print('Confusion Matrix: \n',cm)
acc = accuracy_score(test_y, test_y_classes)
print('Accuracy: ',acc)

#Calculate Accuracy on non plagiarsm
preds_y_pg=test_y_classes>1
test_y_pg=test_y > 1
## print out the array of predicted and true labels, if you want
print('\nPredicted class labels: ')
print(test_y_classes)
print('\nTrue class labels: ')
print(test_y.values)

Confusion Matrix: 
 [[10  0  0  0]
 [ 0  2  2  1]
 [ 0  1  1  3]
 [ 0  0  0  5]]
Accuracy:  0.72

Predicted class labels: 
[3 3 2 1 2 3 0 0 0 0 0 0 1 3 3 2 1 3 0 3 0 3 3 0 0]

True class labels: 
[3. 3. 1. 1. 2. 2. 0. 0. 0. 0. 0. 0. 1. 2. 3. 1. 2. 3. 0. 3. 0. 1. 2. 0.
 0.]


In [39]:
test_y_pg

0      True
1      True
2     False
3     False
4      True
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13     True
14     True
15    False
16     True
17     True
18    False
19     True
20    False
21    False
22     True
23    False
24    False
Name: 0, dtype: bool

In [14]:
sum(test_y_classes == test_y)
n_classes=4
results= np.zeros((n_classes, n_classes))

for i in range(n_classes):
    results[i,i]

19

In [40]:
import numpy as np

# code to evaluate the test predictions vs test labels
# returns a variety of model metrics
def evaluate(test_preds, test_labels, verbose=True):
    """
    Evaluate a model on a test set given the prediction endpoint.  
    Return binary classification metrics.
    :param predictor: A prediction endpoint
    :param test_features: Test features
    :param test_labels: Class labels for test data
    :param verbose: If True, prints a table of all performance metrics
    :return: A dictionary of performance metrics.
    """
    
    # calculate true positives, false positives, true negatives, false negatives
    tp = np.logical_and(test_labels, test_preds).sum()
    fp = np.logical_and(1-test_labels, test_preds).sum()
    tn = np.logical_and(1-test_labels, 1-test_preds).sum()
    fn = np.logical_and(test_labels, 1-test_preds).sum()
    
    # calculate binary classification metrics
    recall = tp / (tp + fn)
    precision = tp / (tp + fp)
    accuracy = (tp + tn) / (tp + fp + tn + fn)
    
    # print metrics
    if verbose:
        print(pd.crosstab(test_labels, test_preds, rownames=['actuals'], colnames=['predictions']))
        print("\n{:<11} {:.3f}".format('Recall:', recall))
        print("{:<11} {:.3f}".format('Precision:', precision))
        print("{:<11} {:.3f}".format('Accuracy:', accuracy))
        print()
        
    return {'TP': tp, 'FP': fp, 'FN': fn, 'TN': tn, 
            'Precision': precision, 'Recall': recall, 'Accuracy': accuracy}


In [41]:
# get metrics for custom predictor and show confussion matrix and metrics
metrics = evaluate(np.squeeze(preds_y_pg), test_y_pg, True)

predictions  False  True 
actuals                  
False           12      3
True             1      9

Recall:     0.900
Precision:  0.750
Accuracy:   0.840



### Question 1: How many false positives and false negatives did your model produce, if any? And why do you think this is?

**Answer**: As we can observe, false positives and false negatives are equal to 0. Our estimator reach a 100% accuracy, precision and recall so it might be overfitting. We have no more samples to evaluate so if we publish the model in production we would need to monitor and verify that outputs are as they are expected to be. if not we should retrain the model with new data or features or maybe using a different model.

### Question 2: How did you decide on the type of model to use? 

** Answer**: I have tested some different algorithms and a linear Support Vector Machine has been choosen. Its performance is better than many decision tree models included ensembled ones as Gradient boosted. I have tested a Pytorch model too, a 2-layer fully connected network, and I get the same results so I decided to use the SVC estimator because it is simpler and faster to train and predict. If we need to apply changes we can do it very easily.

----
## EXERCISE: Clean up Resources

After you're done evaluating your model, **delete your model endpoint**. You can do this with a call to `.delete_endpoint()`. You need to show, in this notebook, that the endpoint was deleted. Any other resources, you may delete from the AWS console, and you will find more instructions on cleaning up all your resources, below.

In [42]:
# uncomment and fill in the line below!
predictor.delete_endpoint()

### Deleting S3 bucket

When you are *completely* done with training and testing models, you can also delete your entire S3 bucket. If you do this before you are done training your model, you'll have to recreate your S3 bucket and upload your training data again.

In [ ]:
# deleting bucket, uncomment lines below

# bucket_to_delete = boto3.resource('s3').Bucket(bucket)
# bucket_to_delete.objects.all().delete()

### Deleting all your models and instances

When you are _completely_ done with this project and do **not** ever want to revisit this notebook, you can choose to delete all of your SageMaker notebook instances and models by following [these instructions](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-cleanup.html). Before you delete this notebook instance, I recommend at least downloading a copy and saving it, locally.

---
## Further Directions

There are many ways to improve or add on to this project to expand your learning or make this more of a unique project for you. A few ideas are listed below:
* Train a classifier to predict the *category* (1-3) of plagiarism and not just plagiarized (1) or not (0).
* Utilize a different and larger dataset to see if this model can be extended to other types of plagiarism.
* Use language or character-level analysis to find different (and more) similarity features.
* Write a complete pipeline function that accepts a source text and submitted text file, and classifies the submitted text as plagiarized or not.
* Use API Gateway and a lambda function to deploy your model to a web application.

These are all just options for extending your work. If you've completed all the exercises in this notebook, you've completed a real-world application, and can proceed to submit your project. Great job!